### ISSUE TITLE
YY: Won't build vpk

### ISSUE THREAD

**Issue by nyathea** [DRok17/Multi-Builder#13]
It says "a duplicate file name exists or the file cannot be found" and the program closes

**Comment by DRok17** [comment]
You might need to re-download and re-extract. If that doesn't work then send me screenshots on your input folder

**Comment by nyathea** [comment]
I did that and it worked the VPK was made but now when launched the game just shows error c-12828-1 on boot but it works fine when ran through yoyoloader

**Comment by DRok17** [comment]
Could be an eboot problem, best to use the updater and rebuild the vpk. Which game is this for?

**Comment by nyathea** [comment]
Im trying to build the vpk for a game called "holocure" it runs fine on yoyoloader. I will try the updater and see if that changes anything

**Comment by DRok17** [comment]
Ok, let me know if it works. If not I'll need the game files or the name of the game used for asset swap

**Comment by DRok17** [comment]
Nevermind, I found the APK. Submitted an issue to Rinne here https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/619#issuecomment-1185077966
He'll need to resolve it.

**Comment by BrickCrypt** [comment]
@DRok17 its possible to create an optimized bubble with asset externalization and compressed textures?
i tried to locate the pvr files in the folder generated by the bubble but still doesnt load the externalized textures and sounds.

**Comment by DRok17** [comment]
> @DRok17 its possible to create an optimized bubble with asset externalization and compressed textures? i tried to locate the pvr files in the folder generated by the bubble but still doesnt load the externalized textures and sounds.

I'll open a separate issue for that one https://github.com/DRok17/Multi-Builder/issues/15. I was also having issues and it's been a while since I've used YoYo Loader

**Comment by DRok17** [comment]
Should be resolved in https://github.com/DRok17/Multi-Builder/commit/aee94fcf83e0586345f7cf6f3484694fb335959b
