### ISSUE TITLE
FB: 1.6 has the exact same issue as 1.5.

### ISSUE THREAD

**Issue by BonQerss** [DRok17/Multi-Builder#14]
As mentioned in #13, building a VPK no longer works for any builder. When it finishes the "Image Conversion" process, it spits out a "cannot find file specified" string at the top. Attempting to continue and build the VPK, yields nothing except it stopping. Same issue as 1.5.

**Comment by DRok17** [comment]
What builder are you using when this occurs?

**Comment by DRok17** [comment]
Should be resolved in https://github.com/DRok17/Multi-Builder/commit/aee94fcf83e0586345f7cf6f3484694fb335959b
