### ISSUE TITLE
No VPK is build for Flycast Builder

### ISSUE THREAD

**Issue by MDashK** [DRok17/Multi-Builder#16]
Trying to build a Flycast bubble is not possible. No VPK file is being created.

![image](https://user-images.githubusercontent.com/20628551/186737794-c21c5190-7b52-4da4-98f9-f4856c4bdb47.png)

![image](https://user-images.githubusercontent.com/20628551/186737811-c0200963-cce6-427d-b6c4-831a1edbb100.png)

![image](https://user-images.githubusercontent.com/20628551/186737832-450ed3a3-4e6d-489e-b472-828e349a1a3e.png)

(I inserted a "Pause" there in the end, just to know the output, or else the window would just close and show nothing).

**Comment by MDashK** [comment]
nevermind, saw the issue. bg file needs to be "bg.png" instead of "bg**0**.png"

**Comment by LaCuche3000** [comment]
Same problem here, but no solution on my side…
The application stops when I enter the rom name :/ (star wars episode 1 racer on cdi format)
