### ISSUE TITLE
vpk does not cloes its self out after opening retroarch

### ISSUE THREAD

**Issue by barrywilcox** [DRok17/Multi-Builder#2]
what happens: when you use the vpk bubble shortcut on the vita,  the  vpk opens up retroarch using the core and rom file selected, but does not close it's self after opening retroarch

what should happen:  the vpk should close its self  once retro arch is running. 

workaround:  I'm having to manually close the launcher bubble vpk out every time I'm done playing an emulated game on retroarch.

**Comment by barrywilcox** [comment]
I also want to add that adrenaline bubble manager does have this feature,   it closes its self out when it launches the game under adrenaline.      so  there should be a way to implement it.

**Comment by DRok17** [comment]
Binary files (the included eboot.bin files) are provided by the developers of RetroArch and Daedalusx64 respectively. They work by booting said app that accepts the rom.txt and core.txt files from the source bubble that you've launched. Unless they decide to implement some code that closes the VPK bubble on launch, there's not much I can do.

From what I know, ABM and Adrenaline both utilize the pre-existing PS1/PSP functionality that is within Vita's filesystem. For example, downloading a PS1/PSP game from the PSN Store is no different from generating the same game using ABM (other than the obvious Title ID and images).

So no, ABM games do not boot using Adrenaline but rather launch directly into the game. That same workflow is just not possible for RetroArch and Daedalusx64 or any Homebrew app that uses the bubble-booter method.

Similarly, launching the same game using Adrenaline launches directly into the game and doesn't require a VPK bubble at all. Technically you're still running said game within the Adrenaline app in that instance.
