### ISSUE TITLE
multi-builer vpk's will not uninstall.  error code generated

### ISSUE THREAD

**Issue by barrywilcox** [DRok17/Multi-Builder#3]
what happens : long press and delete ,   it starts to delete and then gives an error code (does not delete the bubble)

workaround:  none that is simple. the only one you can do is manually go into vitashell and remove all of the vpk files manually and then reboot the vita into safe mode and rebuild the database

**Comment by DRok17** [comment]
Can you forward the VPK in question that does this?

**Comment by barrywilcox** [comment]
> 
> 
> Can you forward the VPK in question that does this?

I would do that but I deleted the package and the entire toolset after that,  I was upset that I had to rebuild my database to fix the uninstall.  

I can tell you it was just a plain pokemon GBA rom that I setup paths manually through the tool.    it worked fine but the bubble would not uninstall.

**Comment by DRok17** [comment]
Sounds more like an unrelated database problem. If this does happen again, please save the VPK for review.
