### ISSUE TITLE
YY: .ini support?

### ISSUE THREAD

**Issue by SofyUchiha** [DRok17/Multi-Builder#9]
Excuse me, does this app support .ini files (for yoyoloader keymaps)? I can't get it to work.
Thank you!

**Comment by DRok17** [comment]
Yup, it's supported. Where are you placing the INI file?

**Comment by SofyUchiha** [comment]
Input folder as "keys.ini"

**Comment by DRok17** [comment]
Does a VPK generate at all?

**Comment by DRok17** [comment]
Any luck getting key maps to work?

**Comment by DRok17** [comment]
@SofyUchiha Going to need more information from you, otherwise, I'll have to close the issue.

Be best to send a screenshot of your input folder and the VPK that was generated.

**Comment by SofyUchiha** [comment]
Sorry, I've been so busy figuring out things from college that I thought I had replied to you. It turns out that it seemed to be the apk, I tried another one and it seems correct. I'm sorry, again.

**Comment by DRok17** [comment]
All good, glad the issue got sorted!
